algoritmo "Ex013_Fibonacci"
// Função :
// Autor :
// Data : 06/07/2020
// Seção de Declarações 
var
   c, t1, t2, t3 : inteiro
funcao proximofibonacci(var a,b: inteiro): inteiro
var
   n3 : inteiro
inicio
      n3 <- n1 + n2
      n1 <- n2
      n3 <- n3
      retorne n3
fimfuncao
inicio
// Seção de Comandos 
   t1 <- 0
   escreva (t1)
   t2 <- 1
   escreva(t2)
   para c := 3 ate 10 faca
       t3 <- proximofibonacci(t1,t2)
       escreval (T3)
   fimpara


fimalgoritmo
