algoritmo "semnome"
// Função :
// Autor :
// Data : 07/07/2020
// Seção de Declarações 
var
   x, y : inteiro
procedimento soma (var a , b : inteiro)
inicio
      a <- a + 1
      b <- b + 1
      escreval("Valor de A = ", a)
      escreval("Valor de B = ", b)
      escreval("Valor de C = ", c)
fimprocedimento
inicio
// Seção de Comandos
   x <- 4
   y <- 8
   escreval("Valor de X = ", x)
   escreval("valor de Y = ", y)
fimalgoritmo
