algoritmo "ex001_soma"
// Função : Soma de dois numeros
// Autor : henrique
// Data : 24/06/2020
// Seção de Declarações 
var
n1, n2, soma: inteiro
media: real

inicio
// Seção de Comandos 
escreva("Informe 1º número:")
leia(n1)
escreva("Informe 2º número:")
leia(n2)
soma <- n1 + n2
media <- (n1 + n2)/2
escreval("A soma entre ", n1, " + ", n2, " = ", soma)
escreva("A média entre ", n1, " e ", n2,"é igual ", media)
fimalgoritmo
